variable:
    create:
        # Scrollie.overrideLimit.MaxScrolls
        MaxScrolls: 20
        ScrollDestination:
            # If players wanted to make a scroll, 
            # and some of the variables are no longer valid due to config.yml changes,
            # default value will be applied.
            # Expected string, must be one of Enabled destinations.
            Default: "Spawn"
            Enabled:
            # EssentialSpawn, then fall back to world spawn.
            - "Spawn"
            # Bed home only
            - "Home"
            # Requires Faction 2.3.x or up. It's time to update to new versions folks!
            - "FactionHome"
            - "Player"
            - "CurrentLocation"
            # CrossWorldTP is forced set to no on random scroll.
            - "Random"
            # Self rescue (For noobs) scroll requires no exp nor scroll item, only scroll name is customizable, and CrossWorldTP is forced set to yes.
            # The cool down time is stored in another column. Players are allowed to have only 1 Self rescue scroll in their inventories to prevent command spam.
            # Will teleport players to Essential spawn.
            - "SelfRescue"
            CanCustomize: Yes
            # If players cannot customize the variable, default value will be applied.
        WarmUpTime:
            # Expected >= 0
            Default: 30
            Min: 0
            Max: 60
            CanCustomize: Yes
        CoolDownTime:
            # Expected >= 0
            Default: 1800
            Min: 0
            Max: 3600
            CanCustomize: Yes
        CrossWorldTP:
            Default: No
            CanCustomize: Yes
        TimesBeUsed:
            # Expected >= 1
            Default: 1
            Min: 1
            Max: 9999
            CanCustomize: Yes
        EnterName:
            # Apply only when a scroll name in DB matches at least one of BannedRegexs
            # Expected string
            Default: "My scroll"
            # https://en.wikipedia.org/wiki/Regular_expression
            Regex: "^.{1,20}$"
            BannedRegexs:
            - ".*fuck.*"
            - ".*shit.*"
            - ".*bitch.*"
            - ".*damn.*"
            
    make:
        BanCreative: Yes
        # Default: paper
        # Expected Minecraft item name
        ScrollItem: "paper"
        
        UseEconInsteadOfEXP: No

        # Expected >= 0
        BaseEXPRequired: 50
        # Multiplies the whole equation.
        ScrollDestinationExpFactor:
            Spawn: 1
            Home: 1.3
            FactionHome: 1.3
            Player: 1.5
            CurrentLocation: 1.7
            Random: 1
            # Should be always 0
            SelfRescue: 0
            
        # Extra EXP (warm up): WarmUpEXPBase / (WarmUpTime + WarmUpEXPDenominatorSum) <WarmUpTime is set by player>
        # Case 1: WarmUpEXPBase = 50, WarmUpEXPDenominatorSum = 1, WarmUpTime = 15
        # Extra EXP required = 50 / (15 + 1) = 50/16 = 3.125
        # Case 2: WarmUpEXPBase = 50, WarmUpEXPDenominatorSum = 2, WarmUpTime = 0
        # Extra EXP required = 50 / (0 + 2) = 50/2 = 25
        # Case 3: WarmUpEXPBase = 100, WarmUpEXPDenominatorSum = 1, WarmUpTime = 0
        # Extra EXP required = 100 / (0 + 1) = 100/1 = 100
        WarmUpEXPBase: 200
        # The more the value close to 0, the more extreme the extra EXP required will be. DenominatorSum decides how extreme will it be.
        # Set this to less than 1 to screw your server up.
        WarmUpEXPDenominatorSum: 3
        
        # Similar to above
        CoolDownExpBase: 800
        CoolDownEXPDenominatorSum: 10
        
        # Multiplies the whole equation.
        # Expected >= 1
        CrossWorldTPExpFactor: 1.5
        
        # Permission node: Scrollie.VIP
        VIPExpFactor: 0.5
        
        # Total EXP required = (Base EXP + Extra EXP (warm up) + Extra EXP(cool down) ) * CrossWorldTPExpFactor * VIPExpFactor * Times available * ScrollDestinationExpFactor
    use:
        BanCreative: Yes
        
        # If set to Yes, remaining count will get decreased by 1 on teleportation success/fail.
        # If set to No, remaining count will get decreased by 1 on teleportation success.
        WarmUpFailDoesHarmToScroll: No
        
        # If set to Yes, item will be destroyed when used up.
        # If set to No, an unenchanted item will be returned to player.
        DestroyItemOnNoRemainingTimes: Yes
        
        # The lower the value, the player's warm up process will more be likely to get interrupted.
        # Expected >= 0
        WarmUpInterruptValue: 5
        
        # Requires Factions support
        Factions:
            CantTeleportToEnemyTerritories: Yes
            CantTeleportFromEnemyTerritories: Yes
            OverrideTPToIfSelfFactionPowerIsHigher: Yes
            OverrideTPFromIfSelfFactionPowerIsHigher: Yes
        Player:
            # If set to Yes, plugin will get target player's offline location as destination.
            # If set to No, the scroll can't be used until the target player online.
            # Requires Essentials support
            AllowOfflineTP: No
        Random:
            # If set to Yes, plugin will choose a random location until at least a 3x1 air block is found, (Much slower and have a internal limit of finding 100 times maximum)
            # that means teleporting a player to cavern is possible. (But dangerous because of lava and network latency)
            # If set to No, plugin will choose a random location, teleport player to the highest block. (MinY, MaxY will be ignored)
            UseAlternativeMethod: No
            Default:
                MinX: -1000
                MaxX: 1000
                MinY: 64
                MaxY: 72
                MinZ: -1000
                MaxZ: 1000
            # YourWorldHere:
        RestrictedAreas:
            # Set this to yes to enable global white list, where restricted areas are places where players are allowed to use scrolls.
            WhiteList: No
system:
    # Change this to get you and this plugin eaten by Ender Dragon, not really, seriously.
    PluginVersion: 0.0.1