variable:
    create:
        ScrollDestination:
            # Expected string
            Default: "Spawn"
            Enabled:
            - "Spawn"
            - "Home"
            - "CurrentLocation"
            - "Random"
            # If players cannot customize the variable, default value will be applied.
            CanCustomize: Yes
        WarmUpTime:
            # Expected >= 0
            Default: 10
            Min: 0
            Max: 60
            CanCustomize: Yes
        CoolDownTime:
            # Expected >= 0
            Default: 600
            Min: 0
            Max: 3600
            CanCustomize: Yes
        CrossWorldTP:
            # Expected Yes/No
            Default: No
            CanCustomize: Yes
        TimesBeUsed:
            # Expected >= 1
            Default: 1
            Min: 1
            Max: 9999
            CanCustomize: Yes
        EnterName:
            # Expected string
            Default: "My scroll"
            # Maximum String length.
            # Expected >= 0
            MaxCharacters: 64
    make:
        # Default: paper
        # Expected Minecraft item ID in Dec data format
        ScrollItem: 339
        # Expected Yes/No
        UseEconInsteadOfEXP: No
        
        # Basic EXP = BaseEXPRequired*ScrollDestinationExpFactor
        # Expected >= 0
        BaseEXPRequired: 50
        ScrollDestinationExpFactor:
            # Expected >= 0
            Spawn: 1
            Home: 1
            CurrentLocation: 2
            Random: 1.5
            
        # Extra EXP (warm up): WarmUpEXPBase / (WarmUpTime + WarmUpEXPDenominatorSum) <WarmUpTime is set by player>
        # Case 1: WarmUpEXPBase = 50, WarmUpEXPDenominatorSum = 1, WarmUpTime = 15
        # Extra EXP required = 50 / (15 + 1) = 50/16 = 3.125
        # Case 2: WarmUpEXPBase = 50, WarmUpEXPDenominatorSum = 2, WarmUpTime = 0
        # Extra EXP required = 50 / (0 + 2) = 50/2 = 25
        # Case 3: WarmUpEXPBase = 100, WarmUpEXPDenominatorSum = 1, WarmUpTime = 0
        # Extra EXP required = 100 / (0 + 1) = 100/1 = 100
        WarmUpEXPBase: 50
        # Set this to less than 1 to screw your server up.
        WarmUpEXPDenominatorSum: 1
        
        # Similar to above
        CoolDownExpBase: 50
        CoolDownEXPDenominatorSum: 1
        
        # Multiplies the whole equation.
        # Expected >= 1
        CrossWorldTPExpFactor: 3
        # Total EXP required = (Basic EXP + Extra EXP (warm up) + Extra EXP(cool down) ) * CrossWorldTPExpFactor
    use:
        # If set to Yes, remaining count will get decreased by 1 on teleportation success/fail.
        # If set to No, remaining count will get decreased by 1 on teleportation success.
        # Expected Yes/No
        MovingDoesHarmToScroll: No

system:
    # Change this to get this plugin eaten by Ender Dragon.
    PluginVersion: 0.0.1