variable:
    create:
        # Scrollie.overrideLimit.MaxScrolls
        MaxScrolls: 20
        ScrollDestination:
            # If players wanted to make a scroll, 
            # and some of the variables are no longer valid due to config.yml changes,
            # default value will be applied.
            # Expected string
            # Must be one of those:
            # - "Spawn"
            # - "Home"
            # - "FactionHome"
            # - "Player"
            # - "CurrentLocation"
            # - "Random"
            # - "SelfRescue"
            Default: "Spawn"
            Enabled:
            - "Spawn"
            - "Home"
            - "FactionHome"
            - "Player"
            - "CurrentLocation"
            # CrossWorldTP is forced set to no on random scroll.
            - "Random"
            # Self rescue scroll requires no exp and paper, but only scroll name is customizable, and CrossWorldTP is forced set to yes.
            # Will teleport players to Essential spawn.
            - "SelfRescue"
            CanCustomize: Yes
            # If players cannot customize the variable, default value will be applied.
        WarmUpTime:
            # Expected >= 0
            Default: 30
            Min: 0
            Max: 60
            CanCustomize: Yes
        CoolDownTime:
            # Expected >= 0
            Default: 900
            Min: 0
            Max: 3600
            CanCustomize: Yes
        CrossWorldTP:
            # Expected Yes/No
            Default: No
            CanCustomize: Yes
        TimesBeUsed:
            # Expected >= 1
            Default: 1
            Min: 1
            Max: 9999
            CanCustomize: Yes
        EnterName:
            # Apply only when a scroll name in DB matches at least one of BannedRegexs
            # Expected string
            Default: "My scroll"
            # https://en.wikipedia.org/wiki/Regular_expression
            Regex: "^.{0,32}$"
            BannedRegexs:
            - ".*fuck.*"
            - ".*shit.*"
            - ".*bitch.*"
            - ".*damn.*"
            
    make:
        BanCreative: Yes
        # Default: paper
        # Expected Minecraft item ID in Dec data format
        ScrollItem: 339
        UseEconInsteadOfEXP: No
        
        # Expected >= 0
        BaseEXPRequired: 50
        # Multiplies the whole equation.
        ScrollDestinationExpFactor:
            Spawn: 1
            Home: 1.5
            FactionHome: 1
            Player: 2
            CurrentLocation: 2
            Random: 1
            # Should be always 0
            SelfRescue: 0
            
        # Extra EXP (warm up): WarmUpEXPBase / (WarmUpTime + WarmUpEXPDenominatorSum) <WarmUpTime is set by player>
        # Case 1: WarmUpEXPBase = 50, WarmUpEXPDenominatorSum = 1, WarmUpTime = 15
        # Extra EXP required = 50 / (15 + 1) = 50/16 = 3.125
        # Case 2: WarmUpEXPBase = 50, WarmUpEXPDenominatorSum = 2, WarmUpTime = 0
        # Extra EXP required = 50 / (0 + 2) = 50/2 = 25
        # Case 3: WarmUpEXPBase = 100, WarmUpEXPDenominatorSum = 1, WarmUpTime = 0
        # Extra EXP required = 100 / (0 + 1) = 100/1 = 100
        WarmUpEXPBase: 50
        # Set this to less than 1 to screw your server up.
        WarmUpEXPDenominatorSum: 1
        
        # Similar to above
        CoolDownExpBase: 500
        CoolDownEXPDenominatorSum: 1
        
        # Multiplies the whole equation.
        # Expected >= 1
        CrossWorldTPExpFactor: 3
        
        # Permission node: Scrollie.VIP
        VIPExpFactor: 0.5
        
        # Total EXP required = (Base EXP + Extra EXP (warm up) + Extra EXP(cool down) ) * CrossWorldTPExpFactor * VIPExpFactor * Times available * ScrollDestinationExpFactor
    use:
        BanCreative: Yes
        # If set to Yes, remaining count will get decreased by 1 on teleportation success/fail.
        # If set to No, remaining count will get decreased by 1 on teleportation success.
        WarmUpFailDoesHarmToScroll: No
        
        Factions:
            CantTeleportToEnemyTerritories: Yes
            CantTeleportFromEnemyTerritories: Yes
            OverrideTPToIfSelfFactionPowerIsHigher: Yes
            OverrideTPFromIfSelfFactionPowerIsHigher: Yes
        Player:
            # If set to Yes, plugin will get target player's offline location as destination.
            # If set to No, the scroll can't be used until the target player online.
            # Expected Yes/No
            AllowOfflineTP: Yes
        Random:
            world:
                MinX: -1000
                MaxX: 1000
                MinY: 64
                MaxY: 80
                MinZ: -1000
                MaxZ: 1000
            # YourWorldHere:
        RestrictedAreas:
            # Set this to yes to enable global white list, where restricted areas are places where players are allowed to use scrolls.
            WhiteList: No
system:
    # Change this to get you and this plugin eaten by Ender Dragon, not really, seriously.
    PluginVersion: 0.0.1