name: Scrollie
version: 0.0.1
description: Yet another useless Minecraft Craftbukkit plugin.
author: Saren
website: https://github.com/Shaorune/Scrollie
 
main: net.wtako.Scrollie.Main
# No, shit.
database: false 

commands:
    Scrollie:
        description: Basic command.
        usage: Type /<command> help to get help.
        permission: Scrollie.Use
        permission-message: You are not permitted to use this plugin.

permissions:
    Scrollie.*:
        description: Gives access to all Scrollie commands.
        children:
            Scrollie.Use: True
            Scrollie.OP: True
        default: op
    Scrollie.OP:
        description: Gives access to all Scrollie administrative commands.
        children:
            Scrollie.OverrideLimit: True
            Scrollie.NoExpRequiredToMake: True
            Scrollie.Reload: True
        default: op
    Scrollie.OverrideLimit:
        description: Gives access to override min/max limit set in config.yml.
        default: op
    Scrollie.NoExpRequiredToMake:
        description: Player with this permission doesn't need experience to make scrolls.
        default: op
    Scrollie.Reload:
        description: Reloads the plugin.
        default: op
    Scrollie.Use:
        description: Gives access to basic commands.
        default: true