name: Scrollie
version: 0.0.1
description: Yet another useless Minecraft Craftbukkit plugin.
author: Saren
website: https://gitlab.wtako.net/Saren/Scrollie
 
main: net.wtako.Scrollie.Main
database: true
softdepend: [mcore, Factions, Essentials, Vault, WorldGuard, WorldEdit]

commands:
    Scrollie:
        description: Basic command.
        usage: Type /<command> help to get help.
        permission: Scrollie.use
        permission-message: You are not permitted to use this plugin.

permissions:
    Scrollie.*:
        description: Gives access to all Scrollie commands.
        default: op
    Scrollie.admin:
        description: Gives access to all Scrollie administrative commands.
        children:
            Scrollie.overrideLimit.*: true
            Scrollie.overrideCanCustomize.*: true
            Scrollie.overrideWUCD: true
            Scrollie.noCostRequiredToMake: true
            Scrollie.cantBeTeleportTarget: true
            Scrollie.canUseScrollInRestrictedAreas: true
            Scrollie.reload: true
        default: op
    Scrollie.use:
        description: Gives access to basic command and using scrolls.
        default: true
    Scrollie.make:
        description: People without this permission cannot create nor make any scrolls.
        default: true
    Scrollie.VIP:
        description: Player with this permission need less experience to make scrolls.
        default: no
    Scrollie.canToggleTP:
        description: Gives access to prevent others from teleporting to you.
        default: op
    Scrollie.overrideLimit.*:
        description: Gives access to override all min/max limit set in config.yml.
        default: op
    Scrollie.overrideCanCustomize.*:
        description: Gives access to override all CanCustomize in config.yml.
        default: op
    Scrollie.overrideWUCDCWTP:
        description: Gives access to override Warm up, Cool down and CWTP.
        default: op
    Scrollie.noCostRequiredToMake:
        description: Player with this permission doesn't need experience and item to make scrolls.
        default: op
    Scrollie.cantBeTeleportTarget:
        description: Player with this permission will not be teleportation target.
        default: op
    Scrollie.canUseScrollInRestrictedAreas:
        description: Gives access to use scrolls in restricted areas and all factions.
        default: op
    Scrollie.reload:
        description: Reloads the plugin.
        default: op