name: ${name}
artifactId: ${artifactId}
version: ${version}
description: ${description}
author: ${author}
website: ${url}
 
main: ${groupId}.${artifactId}.${mainClass}
database: true
softdepend: [mcore, Factions, Essentials, Vault, WorldGuard, WorldEdit]

commands:
    ${artifactId}:
        description: Basic command.
        usage: Type /<command> help to get help.
        permission: ${artifactId}.use
        permission-message: You are not permitted to use this plugin.

permissions:
    ${artifactId}.*:
        description: Gives access to all ${name} commands.
        default: op
    ${artifactId}.admin:
        description: Gives access to all ${name} administrative commands.
        children:
            ${artifactId}.overrideLimit.*: true
            ${artifactId}.overrideCanCustomize.*: true
            ${artifactId}.overrideWUCD: true
            ${artifactId}.noCostRequiredToMake: true
            ${artifactId}.cantBeTeleportTarget: true
            ${artifactId}.canUseScrollInRestrictedAreas: true
            ${artifactId}.reload: true
        default: op
    ${artifactId}.use:
        description: Gives access to basic command and using scrolls.
        default: true
    ${artifactId}.make:
        description: People without this permission cannot create nor make any scrolls.
        default: true
    ${artifactId}.VIP:
        description: Player with this permission need less experience to make scrolls.
        default: no
    ${artifactId}.canToggleTP:
        description: Gives access to prevent others from teleporting to you.
        default: op
    ${artifactId}.overrideLimit.*:
        description: Gives access to override all min/max limit set in config.yml.
        default: op
    ${artifactId}.overrideCanCustomize.*:
        description: Gives access to override all CanCustomize in config.yml.
        default: op
    ${artifactId}.overrideWUCDCWTP:
        description: Gives access to override Warm up, Cool down and CWTP.
        default: op
    ${artifactId}.noCostRequiredToMake:
        description: Player with this permission doesn't need experience and item to make scrolls.
        default: op
    ${artifactId}.cantBeTeleportTarget:
        description: Player with this permission will not be teleportation target.
        default: op
    ${artifactId}.canUseScrollInRestrictedAreas:
        description: Gives access to use scrolls in restricted areas and all factions.
        default: op
    ${artifactId}.reload:
        description: Reloads the plugin.
        default: op